#Production namespace
apiVersion: v1
kind: Namespace
metadata:
  name:  production
---
#Test secret
apiVersion: v1
kind: Secret
metadata:
  name:  db-secret
  namespace: production
data:
   username:  ZGJhZG1pbg==
   password:  UGFzc3dvcmQ=
   dbname: c3Jtc3lzdGVt
type: Opaque

---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100M
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: production
  labels:
    app: pvc-postgres
  name: postgres-pvc
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100M

# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   namespace: production
#   name: postgres-pvc
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 2Gi

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: production
  name: postgres
spec:
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - image: postgres:9.6.2
        name: postgresql
        env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: dbname
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: password
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-pv-claim
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-pv-claim
        persistentVolumeClaim:
          claimName: pvc-postgres

---
kind: Service
apiVersion: v1
metadata:
  namespace: production
  name: srmsystemdb
spec:
  selector:
    app: postgres
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
