apiVersion: v1
kind: Pod
metadata:
  name: database-test
  labels:
    app: db-postgre
spec:
  # initContainers:
  # - name: check-db-ready
  #   image: akubrachenko/kub-db:1.0
  #   command: ['sh', '-c', 'until pg_isready -h database-test -p 5432; do echo waiting for database; sleep 2; done;']
  containers:
  - image: akubrachenko/kub-db:1.0
    name: postgresql
    ports:
    - containerPort: 5432
---
kind: Service
apiVersion: v1
metadata:
  name: srmsystemdb
spec:
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
