---
apiVersion: v1
kind: Secret
metadata:
  name: prod-route53-credentials-secret
  namespace: cert-manager
type: Opaque
data:
  secret-access-key: {{ .Values.secretkey }}

---
#Cluster issuer
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
  namespace: kube-system
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: boy.with.nitro@gmail.com
    privateKeySecretRef:
      key: ""
      name: letsencrypt-production
    dns01:
      providers:
      - name: srm
        route53:
          accessKeyID: {{ .Values.accesskey }}
          region: eu-west-1
          secretAccessKeySecretRef:
            name: prod-route53-credentials-secret
            key: secret-access-key

---
#Certificate
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: srm-certificate
  namespace: istio-system
spec:
  acme:
    config:
    - dns01:
        provider: srm
      domains:
      - '*.cooki3.com'
  commonName: '*.cooki3.com'
  dnsNames:
  - '*.cooki3.com'
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-production
  secretName: istio-ingressgateway-certs